FROM ubuntu:16.04

USER root
RUN apt-get update --fix-missing
RUN apt-get install -y vim
RUN apt-get install -y nginx
RUN apt-get install -y git
RUN apt-get install -y python3-dev
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-setuptools
RUN apt-get install -y libmysqlclient-dev

RUN apt-get install -y libltdl-dev libssl-dev libffi-dev libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk libxml2-dev libxslt1-dev

RUN apt-get install -y libpcre3 libpcre3-dev

ADD django-styleshare/ /root/

RUN pip3 install -r /root/requirements.txt

WORKDIR /root/
EXPOSE 8000
EXPOSE 22



